Play travis
Otus-DevOps-2022-05/yury-z_infra pull request #1
Opened 2022-06-17 21:28 UTC by yury-z

play-travis for integration with github

2022-06-18 13:41 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с материалами методички
Нехватает большого количества файлов
ДЗ возвращаю на доработку

2022-06-21 09:17 UTC, mrgreyves requested changes
Смотрим на результаты тестов =)

2022-06-21 22:06 UTC, yury-z commented
Тесты прошли

2022-06-22 15:45 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-06-28 20:00 UTC, merged