HW packer-base
Otus-DevOps-2022-05/yury-z_infra pull request #5
Opened 2022-08-01 22:25 UTC by yury-z

# Выполнено ДЗ №7

 - [ X ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создан файл описания создания образа Packer ubuntu16.json
 
## Как запустить проект:
 - заполнить файл variables.json
 - выполнить packer build -var-file variables.json ./ubuntu16.json в директории packer

## Как проверить работоспособность:
 - Создать ВМ на основе образа reddit-base
 - Установить git, приложение
 - Запустить приложение и перейти по ссылке http://external_ip:9292

## PR checklist
 - [ X ] Выставил label с номером домашнего задания
 - [ X ] Выставил label с темой домашнего задания

2022-08-02 08:59 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно поправить файл с переменными =)

2022-08-02 08:59 UTC, mrgreyves commented on packer/variables.json.examples
> +{
variables.json.example поставьте вот такое название =)

2022-08-02 20:58 UTC, yury-z commented
Переименовал, но key.json не находит

2022-08-03 08:15 UTC, mrgreyves requested changes
Так все правильно
key.json он и не найдет потому что его нет в репозитории
Нужно добавить ключик с фейковыми значениями

2022-08-04 19:34 UTC, yury-z commented
Да, разобрался

2022-08-05 14:07 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Апрув =)

2022-08-06 09:02 UTC, merged